name: CI
on:
  schedule:
    - cron: '22 4 * * *'
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  validate-node:
    name: 'Validate'
    uses: curium-rocks/flows/.github/workflows/node-ts.yml@main
    secrets:
      SONARQUBE_KEY: ${{ secrets.SONARQUBE_KEY }}
